#include <stdint.h>
#include <string.h>

/* Format of Mmm dd yyyy,  where the names of the months are the same as those
generated by the asctime function and the first character of dd is a space
character if the value is less than 10*/
const char system_build_date[] = {__DATE__};

uint8_t util_get_day_of_month(void) {
  uint8_t day_tens;
  uint8_t day_units;
  uint8_t day;
  uint8_t result;

  // Convert ASCII characters to numeric values
  day_tens  = (system_build_date[4] == ' ') ? 0 : (system_build_date[4] - '0');
  day_units = system_build_date[5] - '0';

  // Combine the tens and units to form the final day value
  // if we inline this, the c compiler goofs
  result = (day_tens * 10);
  result += day_units;

  return result;
}

uint8_t util_get_month(void) {

  if (strncmp(system_build_date, "Jan", 3) == 0)
    return 1;
  else if (strncmp(system_build_date, "Feb", 3) == 0)
    return 2;
  else if (strncmp(system_build_date, "Mar", 3) == 0)
    return 3;
  else if (strncmp(system_build_date, "Apr", 3) == 0)
    return 4;
  else if (strncmp(system_build_date, "May", 3) == 0)
    return 5;
  else if (strncmp(system_build_date, "Jun", 3) == 0)
    return 6;
  else if (strncmp(system_build_date, "Jul", 3) == 0)
    return 7;
  else if (strncmp(system_build_date, "Aug", 3) == 0)
    return 8;
  else if (strncmp(system_build_date, "Sep", 3) == 0)
    return 9;
  else if (strncmp(system_build_date, "Oct", 3) == 0)
    return 10;
  else if (strncmp(system_build_date, "Nov", 3) == 0)
    return 11;
  else if (strncmp(system_build_date, "Dec", 3) == 0)
    return 12;
  else
    return 255;
}

uint8_t util_get_year(void) {
  uint8_t year_tens_value;
  uint8_t year_units_value;
  uint8_t result;

  // Convert ASCII characters to numeric values
  year_tens_value  = system_build_date[9] - '0';
  year_units_value = system_build_date[10] - '0';

  // Combine the tens and units to form the final year value
  result = (year_tens_value * 10);
  result += year_units_value;

  return result;
}
