	SECTION code_compiler

	EXTERN	_EZ80_CPY_UHL_TO_EHL
	PUBLIC	_EZ80_CPY_AUBC_TO_DEHL

_EZ80_CPY_AUBC_TO_DEHL:
	DB	$49, $C5				; PUSH.L	BC
	DB	$49, $E1				; POP.L		HL
	CALL	_EZ80_CPY_UHL_TO_EHL
	LD	D, A
	RET
