#!/bin/sh

# Wrapper for git add that replaces Z:\ZDS with c:\zds in .linkcmd files before staging

files=$(find . \( -name "*.linkcmd" -o -name "*.mak" \) -type f)


# Replace all occurrences of Z:\ZDS with c:\zds
for f in $files; do
    if grep -qi 'c:\\zds' "$f"; then
        sed -i 's|c:\\zds|Z:\\ZDS|gI' "$f"
        echo "corrected: c:\zds -> Z:\ZDS : $f"
    fi
done


# Now call git add with all arguments
git add "$@"
