remote_theme: pages-themes/leap-day@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-feed
title: eZ80 for RC
description: An eZ80 CPU Module designed for the RCBus and RC2014™ ecosystem
author: Dean Netherton
github_username:  dinoboards
