#include <eZ80.h>

#define MPGSEL_0	(*(XSFR)0xFF78)		/* Z2 MEM MGR BANK 0 PAGE SELECT REG (WRITE ONLY)*/
#define MPGSEL_1	(*(XSFR)0xFF79)		/* Z2 MEM MGR BANK 1 PAGE SELECT REG (WRITE ONLY)*/
#define MPGSEL_2	(*(XSFR)0xFF7A)		/* Z2 MEM MGR BANK 2 PAGE SELECT REG (WRITE ONLY)*/
#define MPGSEL_3	(*(XSFR)0xFF7B)		/* Z2 MEM MGR BANK 3 PAGE SELECT REG (WRITE ONLY)*/
#define MPGENA		(*(XSFR)0xFF7C)		/* Z2 MEM MGR PAGING ENABLE REGISTER (BIT 0, WRITE ONLY)*/


void ROMRAM512Init() {
  MPGENA = 1;
  MPGSEL_0 = 0;
  MPGSEL_1 = 1;
  MPGSEL_2 = 64 - 2;
  MPGSEL_3 = 64 - 1;
}
