name: ez80-for-rc

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

jobs:
  ez80-for-rc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: pull docker tool chain
        run: |
          docker pull dinoboards/ez80-rc-builder:0.0.1
          docker pull z88dk/z88dk
          docker pull dinoboards/pipico:0.0.1

      - name: programmer build
        run: |
          docker run -v ./programmer:/programmer/ --privileged=true -t dinoboards/pipico:0.0.1 /bin/bash -c "mkdir -p build && cd build && cmake .. && make"

      - name: Archive Programmer PI Pico Firmware
        uses: actions/upload-artifact@v4
        with:
          compression-level: 0
          name: pi-pico-firmware
          path: |
            programmer/build/programmer.uf2

      - name: firmware make-debug
        env:
          DISPLAY: :1
        run: docker run --rm -v ./firmware:/ez80-for-rc/firmware --privileged=true -t dinoboards/ez80-rc-builder:0.0.1 wine cmd.exe /c "make-debug.bat"

      - name: firmware make-alt-debug
        run: docker run --rm -v ./firmware:/ez80-for-rc/firmware --privileged=true -t dinoboards/ez80-rc-builder:0.0.1 wine cmd.exe /c "make-alt-debug.bat"

      - name: firmware make-release
        run: docker run --rm -v ./firmware:/ez80-for-rc/firmware --privileged=true -t dinoboards/ez80-rc-builder:0.0.1 wine cmd.exe /c "make-release.bat"

      - name: firmware make-alt-release
        run: docker run --rm -v ./firmware:/ez80-for-rc/firmware --privileged=true -t dinoboards/ez80-rc-builder:0.0.1 wine cmd.exe /c "make-alt-release.bat"

      - name: Archive firmware
        uses: actions/upload-artifact@v4
        with:
          compression-level: 0
          name: firmware
          path: |
            firmware/bin

      - name: build apps
        run: docker run -v ./apps:/src/ -t z88dk/z88dk make apps -j RELEASE=true

      - name: Archive apps
        uses: actions/upload-artifact@v4
        with:
          compression-level: 0
          name: apps
          path: |
            apps/bin/release/*.COM
