name: ez80-for-rc

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  hardware:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Apply REVISION_VERSION
        run: |
          VERSION_FILE="./firmware/src/version.inc"
          sed -i "s/REVISION_VERSION\s*.EQU\s*[0-9]*/REVISION_VERSION .EQU ${GITHUB_RUN_NUMBER}/" $VERSION_FILE

      - name: pull docker tool chain
        run: |
          docker pull dinoboards/wincupl:0.0.1

      - name: build hardware jed file
        run: |
          docker run -v ./hardware/:/ez80-for-rc/hardware/ --privileged=true -t dinoboards/wincupl:0.0.1 ./make-jed.sh

      - name: Archive hardware
        uses: actions/upload-artifact@v4
        with:
          compression-level: 0
          name: hardware
          path: |
            hardware/bin

  firmware:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Apply REVISION_VERSION
        run: |
          VERSION_FILE="./firmware/src/version.inc"
          sed -i "s/REVISION_VERSION\s*.EQU\s*[0-9]*/REVISION_VERSION .EQU ${GITHUB_RUN_NUMBER}/" $VERSION_FILE

      - name: Read version numbers
        id: read_version
        run: |
          MAJOR_VERSION=$(grep 'MAJOR_VERSION' ./firmware/src/version.inc | awk '{print $3}')
          MINOR_VERSION=$(grep 'MINOR_VERSION' ./firmware/src/version.inc | awk '{print $3}')
          PATCH_VERSION=$(grep 'PATCH_VERSION' ./firmware/src/version.inc | awk '{print $3}')
          REVISION_VERSION=$(grep 'REVISION_VERSION' ./firmware/src/version.inc | awk '{print $3}')
          echo "MAJOR_VERSION=$MAJOR_VERSION" >> $GITHUB_ENV
          echo "MINOR_VERSION=$MINOR_VERSION" >> $GITHUB_ENV
          echo "PATCH_VERSION=$PATCH_VERSION" >> $GITHUB_ENV
          echo "REVISION_VERSION=$REVISION_VERSION" >> $GITHUB_ENV
          cat  ./firmware/src/version.inc

      - name: pull docker tool chain
        run: |
          docker pull dinoboards/ez80-rc-builder:0.0.1

      - name: firmware make-debug
        run: docker run --rm -e CI=${CI} -v ./:/ez80-for-rc --privileged=true -t dinoboards/ez80-rc-builder:0.0.1 wine cmd.exe /c "cd firmware & make-debug.bat"

      - name: firmware make-release
        run: docker run --rm -e CI=${CI} -v ./:/ez80-for-rc --privileged=true -t dinoboards/ez80-rc-builder:0.0.1 wine cmd.exe /c "cd firmware & make-release.bat"

      - name: Archive firmware
        uses: actions/upload-artifact@v4
        with:
          compression-level: 0
          name: firmware-${{ env.MAJOR_VERSION }}.${{ env.MINOR_VERSION }}.${{ env.PATCH_VERSION }}.${{ env.REVISION_VERSION }}
          path: |
            firmware/bin

      - name: Release HEX file
        uses: actions/upload-artifact@v4
        with:
          compression-level: 0
          name: ez80-rc-firmware-release.hex
          path: |
            firmware/bin/ez80-rc-firmware-release.hex

      - name: Firmware Version File
        uses: actions/upload-artifact@v4
        with:
          compression-level: 0
          name: firmware-version.inc
          path: |
            programmer/firmware-version.inc

  programmer:
    runs-on: ubuntu-latest
    needs: firmware

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: copy ez80-rc-firmware-release.hex
        uses: actions/download-artifact@v4
        with:
          name: ez80-rc-firmware-release.hex
          path: programmer/

      - name: copy version.inc
        uses: actions/download-artifact@v4
        with:
          name: firmware-version.inc
          path: programmer/

      - name: report and version.inc
        run: |
          cat ./programmer/firmware-version.inc

      - name: pull docker tool chain
        run: |
          docker pull dinoboards/pipico:0.0.2

      - name: programmer build
        run: |
          docker run -v ./programmer:/programmer/ --privileged=true -t dinoboards/pipico:0.0.2 /bin/bash -c "mkdir -p build && cd build && cmake .. && make"

      - name: Archive Programmer PI Pico Firmware
        uses: actions/upload-artifact@v4
        with:
          compression-level: 0
          name: pi-pico-firmware
          path: |
            programmer/build/programmer.uf2

  apps:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Apply REVISION_VERSION
        run: |
          VERSION_FILE="./firmware/src/version.inc"
          sed -i "s/REVISION_VERSION\s*.EQU\s*[0-9]*/REVISION_VERSION .EQU ${GITHUB_RUN_NUMBER}/" $VERSION_FILE

      - name: pull docker tool chain
        run: |
          docker pull z88dk/z88dk

      - name: install ez80-clang
        run: |
          wget --progress=dot:giga https://github.com/dinoboards/ez80-clang/releases/download/v0.0.13-rc.94/ez80-clang-v0.0.13-rc.94.tar.gz
          tar -xzvf ez80-clang-v0.0.13-rc.94.tar.gz
          cd ez80-clang-v0.0.13-rc.94
          sudo ./install.sh

      - name: build apps
        working-directory: apps
        run: |
          source /home/runner/.ez80-clang
          make

      - name: Archive apps
        uses: actions/upload-artifact@v4
        with:
          compression-level: 0
          name: apps
          path: |
            apps/bin/*.COM
            apps/bin/*.EXE

  release-notes:
    runs-on: ubuntu-latest
    needs:
      - hardware
      - firmware
      - programmer
      - apps

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Apply REVISION_VERSION
        run: |
          VERSION_FILE="./firmware/src/version.inc"
          sed -i "s/REVISION_VERSION\s*.EQU\s*[0-9]*/REVISION_VERSION .EQU ${GITHUB_RUN_NUMBER}/" $VERSION_FILE

      - name: create release notes
        run: ./release-notes.sh

      - name: Archive release notes
        uses: actions/upload-artifact@v4
        with:
          compression-level: 0
          name: release-notes
          path: |
            releases/CHANGELOG.md

  test-for-release-tag:
    runs-on: ubuntu-latest
    needs: release-notes

    outputs:
      match: ${{ steps.check_tag.outputs.match }}

    steps:
      - name: Check if release tag applied
        id: check_tag
        run: |
          if [[ ${{ github.ref_name }} =~ ^[0-9]{4}-[0-9]{2}-[0-9]{2}$ ]]; then
            echo "match=true" >> $GITHUB_OUTPUT
          else
            echo "match=false" >> $GITHUB_OUTPUT
          fi

  create-draft-release:
    runs-on: ubuntu-latest
    needs: test-for-release-tag
    if: needs.test-for-release-tag.outputs.match == 'true'

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Apply REVISION_VERSION
        run: |
          VERSION_FILE="./firmware/src/version.inc"
          sed -i "s/REVISION_VERSION\s*.EQU\s*[0-9]*/REVISION_VERSION .EQU ${GITHUB_RUN_NUMBER}/" $VERSION_FILE

      - name: Read version numbers
        id: read_version
        run: |
          MAJOR_VERSION=$(grep 'MAJOR_VERSION' ./firmware/src/version.inc | awk '{print $3}')
          MINOR_VERSION=$(grep 'MINOR_VERSION' ./firmware/src/version.inc | awk '{print $3}')
          PATCH_VERSION=$(grep 'PATCH_VERSION' ./firmware/src/version.inc | awk '{print $3}')
          REVISION_VERSION=$(grep 'REVISION_VERSION' ./firmware/src/version.inc | awk '{print $3}')
          echo "MAJOR_VERSION=$MAJOR_VERSION" >> $GITHUB_ENV
          echo "MINOR_VERSION=$MINOR_VERSION" >> $GITHUB_ENV
          echo "PATCH_VERSION=$PATCH_VERSION" >> $GITHUB_ENV
          echo "REVISION_VERSION=$REVISION_VERSION" >> $GITHUB_ENV

      - name: Download hardware artifact
        uses: actions/download-artifact@v4
        with:
          name: hardware
          path: ./hardware/bin

      - name: Download firmware artifact
        uses: actions/download-artifact@v4
        with:
          name: firmware-${{ env.MAJOR_VERSION }}.${{ env.MINOR_VERSION }}.${{ env.PATCH_VERSION }}.${{ env.REVISION_VERSION }}
          path: ./firmware/bin

      - name: Download programmer artifact
        uses: actions/download-artifact@v4
        with:
          name: pi-pico-firmware
          path: ./programmer/build/

      - name: Download apps artifact
        uses: actions/download-artifact@v4
        with:
          name: apps
          path: apps/bin/release

      - name: Download release notes
        uses: actions/download-artifact@v4
        with:
          name: release-notes
          path: releases

      - name: Create directory structure and copy files
        run: |
          mkdir -p releases/firmware
          mkdir -p releases/hardware
          mkdir -p releases/programmer
          mkdir -p releases/apps
          cp firmware/bin/* releases/firmware/
          cp hardware/bin/* releases/hardware/
          cp programmer/build/programmer.uf2 releases/programmer/
          cp apps/bin/release/* releases/apps/

      - name: Zip all artifacts
        run: |
          cd releases
          zip -r ../release.zip *

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: release.zip
          body_path: ${{ github.workspace }}/releases/CHANGELOG.md
          draft: true
          prerelease: true
